baseURL = 'https://blog.rewired.moe'
languageCode = 'zh-cn'
title = 'Blog Rewired'
theme = 'kiss'
copyright = 'rewired (c) 2024'
paginate = 7
enableRobotsTXT = true
hasCJKLanguage = true
enableEmoji = true

[params.rss]
includeContent = true         # Includes whole content in rss
authorName = 'Rewired'        # Author full name
authorEmail = 'n@rewired.moe' # Author email

[params.assets]
customCSS = ['rewired.css']

[params.info]
homeTitle = 'Blog Rewired 🍀' # Title for home page
poweredby = false            # Adds powered by hugo and kiss below Copyright
related = false              # Includes related articles at the bottom of the article
codeCopy = false             # Add copy button above code blocks
taxonomiesCount = true       # Add taxonomies count
enableSocial = true          # Adds OpenGraph and Twitter cards

[params.features]
disqusOnDemand = false
mathjax = false
katex = true

[params.social]
rss = "index.xml" # Add this to show RSS button in social.

[params.sections_left]
"https://rewired.moe" = "Landing Page"
"/index.xml" = "RSS"
"/about" = "About"

[taxonomies]
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[blackfriday]
hrefTargetBlank = true
