backend:
  name: git-gateway
  branch: main
media_folder: "static/assets"
public_folder: "/assets"
site_url: https://blog.rewired.moe
logo_url: https://your-site.com/favicon.svg
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter:
      field: menu
      value: main
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Menu", name: "menu", default: "main", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}